export const assets = [
  'js/chart.js',
  'js/chart-calendar.js',
  'js/chart-ranking.js',
  'js/dashboard.js',
  'js/map.js',
  'js/map-filter.js',
  'js/tabbed.js',
  'js/tooltip.js',
  'js/tree-map.js',
  'js/zoomable.js',
  'css/holder.css',
  'css/maps.css',
  'css/legend.css',
  'css/charts.css',
  'leaflet/leaflet.js',
  'leaflet/leaflet.css',
];

export const components = [
  'chart/bar.ts',
  'chart/calendar.ts',
  'chart/line.ts',
  'chart/ranking.ts',
  'chart/scatter.ts',
  'chart/waffle.ts',
  'dashboard.ts',
  'table.ts',
  'graph/line.ts',
  'hierarchy/treemap.ts',
  'map/hex_cartogram.ts',
  'map/svg.ts',
  'map/zoomable.ts',
];
